# Gitleaks Configuration for assistantapp
# https://github.com/gitleaks/gitleaks

title = "Gitleaks Configuration"

# Extend the default gitleaks configuration
[extend]
useDefault = true

# Allow specific test files with mock credentials
[[allowlist]]
description = "Allowlist .env.test with test-only mock credentials"
paths = [
  '''\.env\.test$''',
  '''\.env\.example$''',
  '''backend/\.env\.test$''',
  '''backend/tests/.*\.env$''',
]

[[allowlist]]
description = "Allowlist test fixtures and mocks"
paths = [
  '''tests/.*fixtures/.*''',
  '''tests/.*mocks/.*''',
  '''__mocks__/.*''',
  '''backend/tests/.*fixtures/.*''',
  '''backend/tests/.*mocks/.*''',
  '''backend/__mocks__/.*''',
]

[[allowlist]]
description = "Ignore common false positives"
regexes = [
  # Test placeholders
  '''test_[a-zA-Z0-9_]+_placeholder''',
  '''test_.*_key''',
  '''mock_[a-zA-Z0-9_]+''',
  '''mock_.*_secret''',
  '''fake_[a-zA-Z0-9_]+''',
  '''placeholder_.*_token''',
  # Example/demo strings
  '''example\.com''',
  '''localhost''',
]
