# Gitleaks Configuration for assistantapp backend
# https://github.com/gitleaks/gitleaks

title = "Gitleaks Configuration"

# Extend the default gitleaks configuration
[extend]
useDefault = true

# Allow specific test files with mock credentials
[[allowlist]]
description = "Allowlist .env.test with test-only mock credentials"
paths = [
  '''\.env\.test$''',
]

[[allowlist]]
description = "Allowlist test fixtures and mocks"
paths = [
  '''tests/.*fixtures/.*''',
  '''tests/.*mocks/.*''',
  '''__mocks__/.*''',
]

[[allowlist]]
description = "Ignore common false positives"
regexes = [
  # Test placeholders
  '''test_[a-zA-Z0-9_]+_placeholder''',
  '''mock_[a-zA-Z0-9_]+''',
  '''fake_[a-zA-Z0-9_]+''',
  # Example/demo strings
  '''example\.com''',
  '''localhost''',
]
