export const CALENDAR_SERVICE_CONSTANTS = {
  SERVICE_NAMES: {
    CALENDAR_EVENT_MANAGER: 'calendarEventManager',
    CALENDAR_AVAILABILITY_CHECKER: 'calendarAvailabilityChecker',
    CALENDAR_FORMATTER: 'calendarFormatter',
    CALENDAR_VALIDATOR: 'calendarValidator',
    CALENDAR_SERVICE: 'calendarService',
  },
  ERRORS: {
    CALENDAR_SERVICE_NOT_AVAILABLE: 'CalendarService not available',
    EVENT_SUMMARY_REQUIRED: 'Event summary is required',
    EVENT_START_TIME_REQUIRED: 'Event start time is required',
    EVENT_END_TIME_REQUIRED: 'Event end time is required',
    EVENT_ID_REQUIRED: 'Event ID is required',
    INVALID_DATE_FORMAT: 'Invalid date format',
    START_TIME_AFTER_END_TIME: 'Start time must be before end time',
    EVENT_TOO_LONG: 'Event duration is too long (max 24 hours)',
    EVENT_TOO_SHORT: 'Event duration is too short (min 15 minutes)',
    INVALID_ATTENDEE_EMAIL: 'Invalid attendee email format',
    MAX_ATTENDEES_EXCEEDED: 'Maximum number of attendees exceeded',
    INVALID_LOCATION: 'Invalid location format',
    MISSING_PERMISSIONS: 'Missing calendar permissions',
    NO_ACCESS_TOKEN: 'No access token provided',
    VALIDATION_FAILED: 'Validation failed',
    EVENT_CREATION_FAILED: 'Event creation failed',
    EVENT_UPDATE_FAILED: 'Event update failed',
    EVENT_DELETION_FAILED: 'Event deletion failed',
    EVENT_LISTING_FAILED: 'Event listing failed',
    EVENT_RETRIEVAL_FAILED: 'Event retrieval failed',
    AVAILABILITY_CHECK_FAILED: 'Availability check failed',
    TIME_SLOT_SEARCH_FAILED: 'Time slot search failed',
    CALENDAR_FORMATTING_FAILED: 'Calendar formatting failed',
    UNKNOWN_ERROR: 'Unknown error',
  },
  SUCCESS: {
    EVENT_CREATED: 'Event created successfully',
    EVENT_UPDATED: 'Event updated successfully',
    EVENT_DELETED: 'Event deleted successfully',
    EVENTS_LISTED: 'Events listed successfully',
    EVENT_RETRIEVED: 'Event retrieved successfully',
    AVAILABILITY_CHECKED: 'Availability checked successfully',
    TIME_SLOTS_FOUND: 'Time slots found successfully',
    CALENDAR_OPERATION_COMPLETED: 'Calendar operation completed',
  },
  CALENDAR_OPERATIONS: {
    CREATE: 'create',
    UPDATE: 'update',
    DELETE: 'delete',
    LIST: 'list',
    GET: 'get',
    CHECK_AVAILABILITY: 'check_availability',
    FIND_SLOTS: 'find_slots',
  },
  VALIDATION_TYPES: {
    DATE_FORMAT: 'date_format',
    TIME_RANGE: 'time_range',
    ATTENDEE_EMAIL: 'attendee_email',
    LOCATION: 'location',
    INVALID: 'invalid',
  },
  FORMATTING: {
    EVENT_CREATED_SUCCESS: '✅ **Event created successfully!**',
    EVENT_UPDATED_SUCCESS: '✅ **Event updated successfully!**',
    EVENT_DELETED_SUCCESS: '✅ **Event deleted successfully!**',
    EVENTS_FOUND: '📅 **Found {count} event{plural}**',
    NO_EVENTS_FOUND: '📅 **No events found** for the specified time range.',
    EVENT_DETAILS_HEADER: '📅 **Event Details**',
    EVENT_SUMMARY_LABEL: '📝 **Summary:**',
    EVENT_START_LABEL: '🕐 **Start:**',
    EVENT_END_LABEL: '🕐 **End:**',
    EVENT_LOCATION_LABEL: '📍 **Location:**',
    EVENT_ATTENDEES_LABEL: '👥 **Attendees:**',
    EVENT_DESCRIPTION_LABEL: '📄 **Description:**',
    EVENT_ID_LABEL: '🆔 **Event ID:**',
    AVAILABILITY_HEADER: '⏰ **Availability Check**',
    TIME_SLOTS_HEADER: '🕐 **Available Time Slots**',
    NO_TIME_SLOTS: '❌ **No available time slots** found for the specified criteria.',
  },
  DEFAULTS: {
    MAX_EVENT_DURATION_HOURS: 24,
    MIN_EVENT_DURATION_MINUTES: 15,
    MAX_ATTENDEES: 100,
    DEFAULT_CALENDAR_ID: 'primary',
    UNKNOWN_EVENT: 'Unknown Event',
    NO_LOCATION: 'No location specified',
    NO_DESCRIPTION: 'No description provided',
    UNKNOWN_ERROR: 'Unknown error occurred',
  },
  LIMITS: {
    MAX_DISPLAY_EVENTS: 10,
    MAX_TEXT_TRUNCATE: 500,
    MAX_SUMMARY_LENGTH: 200,
    MAX_DESCRIPTION_LENGTH: 2000,
    MAX_LOCATION_LENGTH: 200,
  },
} as const;
