export const SLACK_SERVICE_CONSTANTS = {
  SERVICE_NAMES: {
    SLACK_MESSAGE_ANALYZER: 'slackMessageAnalyzer',
    SLACK_DRAFT_MANAGER: 'slackDraftManager',
    SLACK_CONFIRMATION_HANDLER: 'slackConfirmationHandler',
    SLACK_FORMATTER: 'slackFormatter',
    SLACK_MESSAGE_READER_SERVICE: 'slackMessageReaderService',
  },
  ERRORS: {
    SLACK_MESSAGE_READER_NOT_AVAILABLE: 'SlackMessageReaderService not available',
    CHANNEL_ID_REQUIRED: 'Channel ID is required',
    THREAD_TS_REQUIRED: 'Thread timestamp is required',
    MESSAGE_TEXT_REQUIRED: 'Message text is required',
    INVALID_CHANNEL_ID: 'Invalid channel ID format',
    INVALID_THREAD_TS: 'Invalid thread timestamp format',
    MESSAGE_READING_FAILED: 'Message reading failed',
    THREAD_READING_FAILED: 'Thread reading failed',
    CONVERSATION_ANALYSIS_FAILED: 'Conversation analysis failed',
    DRAFT_CREATION_FAILED: 'Draft creation failed',
    DRAFT_UPDATE_FAILED: 'Draft update failed',
    DRAFT_DELETION_FAILED: 'Draft deletion failed',
    DRAFT_LISTING_FAILED: 'Draft listing failed',
    CONFIRMATION_DETECTION_FAILED: 'Confirmation detection failed',
    CONFIRMATION_PROCESSING_FAILED: 'Confirmation processing failed',
    SLACK_FORMATTING_FAILED: 'Slack formatting failed',
    UNKNOWN_ERROR: 'Unknown error',
  },
  SUCCESS: {
    MESSAGES_READ: 'Messages read successfully',
    THREAD_READ: 'Thread read successfully',
    CONVERSATION_ANALYZED: 'Conversation analyzed successfully',
    DRAFT_CREATED: 'Draft created successfully',
    DRAFT_UPDATED: 'Draft updated successfully',
    DRAFT_DELETED: 'Draft deleted successfully',
    DRAFTS_LISTED: 'Drafts listed successfully',
    CONFIRMATION_DETECTED: 'Confirmation detected successfully',
    CONFIRMATION_PROCESSED: 'Confirmation processed successfully',
    SLACK_OPERATION_COMPLETED: 'Slack operation completed',
  },
  SLACK_OPERATIONS: {
    READ_MESSAGES: 'read_messages',
    READ_THREAD: 'read_thread',
    ANALYZE_CONVERSATION: 'analyze_conversation',
    MANAGE_DRAFTS: 'manage_drafts',
    DETECT_CONFIRMATIONS: 'detect_confirmations',
    HANDLE_CONFIRMATIONS: 'handle_confirmations',
  },
  FORMATTING: {
    MESSAGES_FOUND: '📨 **Found {count} message{plural}**',
    NO_MESSAGES_FOUND: '📨 **No messages found** in the specified channel.',
    THREAD_MESSAGES_FOUND: '🧵 **Found {count} thread message{plural}**',
    NO_THREAD_MESSAGES: '🧵 **No thread messages found**',
    CONVERSATION_SUMMARY_HEADER: '📊 **Conversation Analysis**',
    CONVERSATION_SUMMARY_LABEL: '📝 **Summary:**',
    KEY_TOPICS_LABEL: '🏷️ **Key Topics:**',
    ACTION_ITEMS_LABEL: '✅ **Action Items:**',
    SENTIMENT_LABEL: '😊 **Sentiment:**',
    PARTICIPANTS_LABEL: '👥 **Participants:**',
    DRAFTS_FOUND: '📝 **Found {count} draft{plural}**',
    NO_DRAFTS_FOUND: '📝 **No drafts found**',
    CONFIRMATION_DETECTED: '✅ **Confirmation detected**',
    CONFIRMATION_PROCESSED: '✅ **Confirmation processed**',
  },
  DEFAULTS: {
    MAX_MESSAGES_DISPLAY: 10,
    MAX_TEXT_TRUNCATE: 500,
    MAX_SUMMARY_LENGTH: 200,
    MAX_TOPICS_DISPLAY: 10,
    MAX_ACTION_ITEMS_DISPLAY: 10,
    UNKNOWN_MESSAGE: 'Unknown Message',
    UNKNOWN_USER: 'Unknown User',
    UNKNOWN_ERROR: 'Unknown error occurred',
  },
  LIMITS: {
    MAX_DISPLAY_MESSAGES: 10,
    MAX_TEXT_TRUNCATE: 500,
    MAX_SUMMARY_LENGTH: 200,
    MAX_TOPICS_LENGTH: 10,
    MAX_ACTION_ITEMS_LENGTH: 10,
  }
} as const;
